name: 'brazelian_e_commerce'
version: '1.0.0'

profile: 'Brazelian_E_Commerce'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  brazelian_e_commerce:
    staging:
      +materialized: view
      +schema: STAGING
      +database: SILVER_DB
    intermediate:
      +materialized: view
      +schema: INTERMEDIATE
      +database: SILVER_DB
    marts:
      facts:
        +materialized: incremental
        +schema: MARTS
        +database: GOLD_DB
      dimensions:
        +materialized: table
        +schema: MARTS
        +database: GOLD_DB