USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS ECOMM_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Main warehouse for ecommerce pipeline';