CREATE ROLE IF NOT EXISTS ECOMM_ENGINEER;
CREATE ROLE IF NOT EXISTS ECOMM_ANALYST;

-- Give engineer access to everything
GRANT USAGE ON WAREHOUSE ECOMM_WH TO ROLE ECOMM_ENGINEER;
GRANT ALL ON DATABASE BRONZE_DB TO ROLE ECOMM_ENGINEER;
GRANT ALL ON DATABASE SILVER_DB TO ROLE ECOMM_ENGINEER;
GRANT ALL ON DATABASE GOLD_DB TO ROLE ECOMM_ENGINEER;

-- Give analyst read-only access to gold only
GRANT USAGE ON WAREHOUSE ECOMM_WH TO ROLE ECOMM_ANALYST;
GRANT USAGE ON DATABASE GOLD_DB TO ROLE ECOMM_ANALYST;

-- Assign engineer role to your user
GRANT ROLE ECOMM_ENGINEER TO USER ANUSARAUDAEN;

-- Switch to engineer role now
USE ROLE ECOMM_ENGINEER;