USE DATABASE BRONZE_DB;
USE SCHEMA RAW_ORDERS;

--Order table
CREATE OR REPLACE TABLE RAW_ORDERS(

    ORDER_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    ORDER_STATUS VARCHAR,
    ORDER_PURCHASE_TIMESTAMP VARCHAR,
    ORDER_APPROVED_AT VARCHAR,
    ORDER_DELIVERED_CARRIER_DATE VARCHAR,
    ORDER_DELIVERED_CUSTOMER_DATE VARCHAR,
    ORDER_ESTIMATED_DELIVERY_DATE VARCHAR,
    _file_name VARCHAR,
    _loaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
    
);

USE SCHEMA RAW_PRODUCTS;

--Product table
CREATE OR REPLACE TABLE RAW_PRODUCTS(

    PRODUCT_ID VARCHAR,
    PRODUCT_CATEGORY_NAME VARCHAR,
    PRODUCT_NAME_LENGTH VARCHAR,
    PRODUCT_DESCRIPTION_LENGTH VARCHAR,
    PRODUCR_PHOTOS_QTY VARCHAR,
    PRODUCT_WEIGHT_G VARCHAR,
    PRODUCT_LENGTH_CM VARCHAR,
    PRODUCT_HEIGHT_CM VARCHAR,
    PRODUCT_WIDTH_CM VARCHAR,
     _file_name VARCHAR,
    _loaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
    
);

USE SCHEMA RAW_SELLERS;
--Create sellers table

CREATE OR REPLACE TABLE RAW_SELLERS(

    SELLER_ID VARCHAR,
    SELLER_ZIP_CODE_PREFIX VARCHAR,
    SELLER_CITY VARCHAR,
    SELLER_STATE VARCHAR,
     _file_name VARCHAR,
    _loaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

USE SCHEMA RAW_PRODUCT_CATEGORY_NAME_TRANSLATION;

--Create PRODUCT_CATEGORY_NAME_TRANSLATION table
CREATE OR REPLACE TABLE RAW_PRODUCT_CATEGORY_NAME_TRANSLATION(

    PRODUCT_CATEGORY VARCHAR,
    PRODUCT_CATEGORY_NAME_ENGLISH VARCHAR,
     _file_name VARCHAR,
    _loaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

USE SCHEMA RAW_CUSTOMERS;

--Create RAW_CUSTOMERS Table
CREATE OR REPLACE TABLE RAW_CUSTOMERS(
    CUSTOMER_ID VARCHAR,
    CUSTOMER_UNIQUE_ID VARCHAR,
    CUSTOMER_ZIP_CODE_PREFIX VARCHAR,
    CUSTOMER_CITY VARCHAR,
    CUSTOMER_STATE VARCHAR,
     _file_name VARCHAR,
    _loaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

USE SCHEMA RAW_GEOLOCATIONS;

--Create RAW_GEOLOCATIONS table
CREATE OR REPLACE TABLE RAW_GEOLOCATIONS(
    GEOLOCATION_ZIP_CODE_PREFIX VARCHAR,
    GEOLOCATION_LAT VARCHAR,
    GEOLOCATION_LNG VARCHAR,
    GEOLOCATION_CITY VARCHAR,
    GEOLOCATION_STATE VARCHAR,
     _file_name VARCHAR,
    _loaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
    
);

USE SCHEMA RAW_ORDER_ITEMS;

-- Create RAW_ORDER_ITEMS table
CREATE OR REPLACE TABLE RAW_ORDER_ITEMS(
    ORDER_ID VARCHAR,
    ORDER_ITEM VARCHAR,
    PRODUCT_ID VARCHAR,
    SELLER_ID VARCHAR,
    SHIPPING_LIMIT_DATE VARCHAR,
    PRICE VARCHAR,
    FREIGHT_VALUE VARCHAR,
     _file_name VARCHAR,
    _loaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

USE SCHEMA RAW_ORDER_PAYMENTS;

--Create RAW_ORDER_PAYMENTS table
CREATE OR REPLACE TABLE RAW_ORDER_PAYMENTS(
    ORDER_ID VARCHAR,
    PAYMENT_SEQUENCE VARCHAR,
    PAYMENT_TYPE VARCHAR,
    PAYMENT_INSTALLMENTS VARCHAR,
    PAYMENT_VALUE VARCHAR,
     _file_name VARCHAR,
    _loaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

USE SCHEMA RAW_ORDER_REVIEWS;

--Create RAW_ORDER_REVIEWS table
CREATE OR REPLACE TABLE RAW_ORDER_REVIEWS(
    REVIEW_ID VARCHAR,
    ORDER_ID VARCHAR,
    REVIEW_SCORE VARCHAR,
    REVIEW_COMMENT_TITLE VARCHAR,
    REVIEW_COMMENT_MESSAGE VARCHAR,
    REVIEW_CREATION_DATE VARCHAR,
    REVIEW_ANSWER_TIMESTAMP VARCHAR,
     _file_name VARCHAR,
    _loaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);