USE DATABASE BRONZE_DB;
USE SCHEMA RAW_ORDERS;  

CREATE OR REPLACE STAGE BRONZE_DB.RAW_ORDERS.AZURE_ECOMMERCE_STAGE
    URL = {URL}
    CREDENTIALS = (AZURE_SAS_TOKEN = {AZURE_SAS_TOKEN})
')
    FILE_FORMAT = (
        TYPE = 'CSV'
        SKIP_HEADER = 1
        FIELD_OPTIONALLY_ENCLOSED_BY = '"'
        NULL_IF = ('NULL', 'null', '')
        EMPTY_FIELD_AS_NULL = TRUE
    );